source 'https://rubygems.org'
gem 'cucumber'
gem 'rspec'
gem 'page-object'
# gem 'capybara-webkit', '1.10.0'
# gem 'selenium-webdriver', '2.53.4'
gem 'capybara-webkit'
gem 'selenium-webdriver'
gem 'rspec-expectations'
gem 'poltergeist'
gem 'gmail'
gem 'capybara-email'
gem 'mechanize'
gem 'site_prism'
gem 'capybara'
gem 'guard-cucumber'
gem 'appium_capybara'
gem 'pry'
gem 'launchy'
gem 'capybara-screenshot'
gem 'rubocop'
gem 'faker'
gem 'capybara-mechanize'
gem 'slack-notifier'
gem 'i18n'
